[versions]
reorderable = "2.4.3"
filekitCompose = "0.8.8"
datastore = "1.1.1"
opencv-jvm = "4.10.0-1.5.11"
jetbrains-lifecycle = "2.8.2"
jSystemThemeDetector = "3.9-SNAPSHOT"

[libraries]
reorderable = { module = "sh.calvin.reorderable:reorderable", version.ref = "reorderable" }
filekit-compose = { module = "io.github.vinceglb:filekit-compose", version.ref = "filekitCompose" }
datastore = { module = "androidx.datastore:datastore", version.ref = "datastore" }
datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }
jetbrains-lifecycle = {module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "jetbrains-lifecycle"}
jvm-opencv ={ module = "org.bytedeco:opencv-platform", version.ref = "opencv-jvm"}
jSystemThemeDetector = {module = "com.github.Dansoftowner:jSystemThemeDetector", version.ref = "jSystemThemeDetector"}
